services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - api
    environment:
      - VITE_API_URL=${VITE_API_URL}

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      # DATABASE_URL=${DATABASE_URL}

volumes: {}
