services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - api

  api:
    build: ./api
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      # DATABASE_URL=${DATABASE_URL}

volumes: {}
