employees = [
    {
        "id": "EMP-0421",
        "name": "A. Laurent",
        "service": "Commercial",
        "tenure": "2 ans 3 mois",
        "score": 0.92,
        "risk": "high",
    },
    {
        "id": "EMP-0187",
        "name": "M. Bernard",
        "service": "Technique",
        "tenure": "1 an 8 mois",
        "score": 0.87,
        "risk": "high",
    },
    {
        "id": "EMP-0334",
        "name": "S. Clément",
        "service": "Finance",
        "tenure": "4 ans",
        "score": 0.71,
        "risk": "high",
    },
    {
        "id": "EMP-0562",
        "name": "P. Dubois",
        "service": "Commercial",
        "tenure": "3 ans 1 mois",
        "score": 0.65,
        "risk": "medium",
    },
    {
        "id": "EMP-0093",
        "name": "E. Martin",
        "service": "RH",
        "tenure": "5 ans 7 mois",
        "score": 0.58,
        "risk": "medium",
    },
    {
        "id": "EMP-0278",
        "name": "C. Fontaine",
        "service": "Technique",
        "tenure": "8 mois",
        "score": 0.54,
        "risk": "medium",
    },
    {
        "id": "EMP-0401",
        "name": "N. Richard",
        "service": "Juridique",
        "tenure": "2 ans",
        "score": 0.49,
        "risk": "medium",
    },
    {
        "id": "EMP-0155",
        "name": "J. Thomas",
        "service": "Direction",
        "tenure": "7 ans 2 mois",
        "score": 0.41,
        "risk": "medium",
    },
    {
        "id": "EMP-0312",
        "name": "L. Girard",
        "service": "Finance",
        "tenure": "3 ans 5 mois",
        "score": 0.28,
        "risk": "low",
    },
    {
        "id": "EMP-0489",
        "name": "R. Petit",
        "service": "Commercial",
        "tenure": "6 ans",
        "score": 0.19,
        "risk": "low",
    },
    {
        "id": "EMP-0210",
        "name": "T. Moreau",
        "service": "RH",
        "tenure": "1 an",
        "score": 0.15,
        "risk": "low",
    },
    {
        "id": "EMP-0367",
        "name": "A. Simon",
        "service": "Technique",
        "tenure": "4 ans 2 mois",
        "score": 0.12,
        "risk": "low",
    },
]

predictions = [
    {
        "employee_id": "EMP-0421",
        "score": 0.92,
        "risk": "high",
        "trend": "up",
        "batch_date": "2026-02-20",
        "shap_factors": [
            {
                "label": "Stagnation de poste",
                "detail": "Aucune évolution depuis 27 mois",
                "contribution": 0.31,
                "positive": True,
            },
            {
                "label": "Absences récentes",
                "detail": "+4 jours vs moyenne du service",
                "contribution": 0.24,
                "positive": True,
            },
            {
                "label": "Aucune formation",
                "detail": "0 formation sur 12 mois",
                "contribution": 0.19,
                "positive": True,
            },
            {
                "label": "Ancienneté 2–3 ans",
                "detail": "Fenêtre de risque critique",
                "contribution": 0.14,
                "positive": True,
            },
            {
                "label": "Contrat CDI",
                "detail": "Stabilité contractuelle",
                "contribution": 0.07,
                "positive": False,
            },
        ],
    },
    {
        "employee_id": "EMP-0187",
        "score": 0.87,
        "risk": "high",
        "trend": "up",
        "batch_date": "2026-02-20",
        "shap_factors": [
            {
                "label": "Mobilité interne",
                "detail": "3 changements de poste en 2 ans",
                "contribution": 0.28,
                "positive": True,
            },
            {
                "label": "Absences récentes",
                "detail": "+6 jours vs moyenne du service",
                "contribution": 0.26,
                "positive": True,
            },
            {
                "label": "Ancienneté 1–2 ans",
                "detail": "Fenêtre de risque critique",
                "contribution": 0.18,
                "positive": True,
            },
            {
                "label": "Aucune formation",
                "detail": "0 formation sur 12 mois",
                "contribution": 0.15,
                "positive": True,
            },
            {
                "label": "Contrat CDI",
                "detail": "Stabilité contractuelle",
                "contribution": 0.07,
                "positive": False,
            },
        ],
    },
    {
        "employee_id": "EMP-0334",
        "score": 0.71,
        "risk": "high",
        "trend": "stable",
        "batch_date": "2026-02-20",
        "shap_factors": [
            {
                "label": "Stagnation de poste",
                "detail": "Aucune évolution depuis 18 mois",
                "contribution": 0.25,
                "positive": True,
            },
            {
                "label": "Ancienneté 3–5 ans",
                "detail": "Fenêtre de risque modérée",
                "contribution": 0.20,
                "positive": True,
            },
            {
                "label": "Absences récentes",
                "detail": "+2 jours vs moyenne du service",
                "contribution": 0.15,
                "positive": True,
            },
            {
                "label": "Contrat CDI",
                "detail": "Stabilité contractuelle",
                "contribution": 0.09,
                "positive": False,
            },
        ],
    },
    {
        "employee_id": "EMP-0562",
        "score": 0.65,
        "risk": "medium",
        "trend": "up",
        "batch_date": "2026-02-20",
        "shap_factors": [
            {
                "label": "Stagnation de poste",
                "detail": "Aucune évolution depuis 12 mois",
                "contribution": 0.22,
                "positive": True,
            },
            {
                "label": "Absences récentes",
                "detail": "+3 jours vs moyenne du service",
                "contribution": 0.18,
                "positive": True,
            },
            {
                "label": "Ancienneté 2–3 ans",
                "detail": "Fenêtre de risque critique",
                "contribution": 0.14,
                "positive": True,
            },
            {
                "label": "Contrat CDI",
                "detail": "Stabilité contractuelle",
                "contribution": 0.08,
                "positive": False,
            },
        ],
    },
    {
        "employee_id": "EMP-0093",
        "score": 0.58,
        "risk": "medium",
        "trend": "stable",
        "batch_date": "2026-02-20",
        "shap_factors": [
            {
                "label": "Ancienneté 5–7 ans",
                "detail": "Risque de lassitude",
                "contribution": 0.20,
                "positive": True,
            },
            {
                "label": "Aucune formation",
                "detail": "1 formation sur 12 mois",
                "contribution": 0.16,
                "positive": True,
            },
            {
                "label": "Stagnation de poste",
                "detail": "Aucune évolution depuis 10 mois",
                "contribution": 0.12,
                "positive": True,
            },
            {
                "label": "Ancienneté élevée",
                "detail": "Facteur de rétention",
                "contribution": 0.10,
                "positive": False,
            },
        ],
    },
]

users = [
    {
        "id": 1,
        "email": "admin@entreprise.fr",
        "password": "admin123",
        "role": "RH_ADMIN",
        "name": "Mme Y",
    },
    {
        "id": 2,
        "email": "rh@entreprise.fr",
        "password": "rh123",
        "role": "RH_STANDARD",
        "name": "C. Vidal",
    },
    {
        "id": 3,
        "email": "manager@entreprise.fr",
        "password": "manager123",
        "role": "MANAGER",
        "name": "P. Rousseau",
    },
]
